USE ROLE SYSADMIN;
USE DATABASE SNOWPROCORE;
USE SCHEMA PUBLIC;
USE WAREHOUSE SNOWPROCORE;

/** CREATE TABLE WITH CLUSTERING **/
CREATE OR REPLACE TRANSIENT TABLE SNOWPROCORE.PUBLIC.EMPLOYEE (
	TYPE VARCHAR(10),
	NAME VARCHAR(10), 
	COUNTRY VARCHAR(20), 
	DATE_C  DATE
) 
CLUSTER BY (DATE_C);

/** IF YOU HAVE ALREADY LOADED DATA **/

ALTER  TABLE SNOWPROCORE.PUBLIC.EMPLOYEE CLUSTER BY (DATE_C);

ALTER  TABLE SNOWPROCORE.PUBLIC.EMPLOYEE RECLUSTER; -- This will give us an error since table is empty

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER LIMIT 100;

/**** CREATE TABLE WITHOUT CLUSTER ***/
ALTER WAREHOUSE SNOWPROCORE SET WAREHOUSE_SIZE = XXLARGE;
CREATE OR REPLACE TRANSIENT TABLE SNOWPROCORE.PUBLIC.EMPLOYEE
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;
ALTER WAREHOUSE SNOWPROCORE SET WAREHOUSE_SIZE = XSMALL;

DESC TABLE SNOWPROCORE.PUBLIC.EMPLOYEE

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTER','(C_MKTSEGMENT)');

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTER','(C_MKTSEGMENT,C_CUSTKEY)');

/**** CREATE TABLE WITH CLUSTER ***/

select get_ddl('TABLE','SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER')

drop table CUSTOMER_CLUSTERED

create or replace transient TABLE CUSTOMER_CLUSTERED (
	C_CUSTKEY NUMBER(38,0) NOT NULL,
	C_NAME VARCHAR(25) NOT NULL,
	C_ADDRESS VARCHAR(40) NOT NULL,
	C_NATIONKEY NUMBER(38,0) NOT NULL,
	C_PHONE VARCHAR(15) NOT NULL,
	C_ACCTBAL NUMBER(12,2) NOT NULL,
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
) CLUSTER BY (C_MKTSEGMENT)

INSERT INTO  SAMPLE_DATABASE.PUBLIC.CUSTOMER_CLUSTERED
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER
-- ORDER BY C_MKTSEGMENT

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_CLUSTERED','(C_MKTSEGMENT)');

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_CLUSTERED');

/** RECLUSTER THE NON CLUSTERED TABLE **/

CREATE OR REPLACE TRANSIENT TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_ORDERED
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER ORDER BY C_MKTSEGMENT

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_ORDERED','(C_MKTSEGMENT)');


/** RECLUSTER TABLE AFTER LOADING DATA **/

SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER

ALTER  TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER BY (C_MKTSEGMENT);

ALTER  TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER RECLUSTER;

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTER','(C_MKTSEGMENT)');

/****** Cardinality of columns **********/

DESC TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER

SELECT C_MKTSEGMENT,COUNT(*) FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER
GROUP BY C_MKTSEGMENT

SELECT C_MKTSEGMENT,C_ADDRESS,COUNT(*) FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER
GROUP BY C_MKTSEGMENT,C_ADDRESS

SELECT COUNT(*) FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER

SELECT DISTINCT C_ADDRESS FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER 

SELECT 238609294/1500000000

SELECT DISTINCT C_MKTSEGMENT FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER

SELECT 5/1500000000