USE ROLE SYSADMIN;

-- Creating a virtual warehouse
CREATE OR REPLACE WAREHOUSE XSMALL WITH
 WAREHOUSE_SIZE = 'XSMALL'
 WAREHOUSE_TYPE = 'STANDARD'
 AUTO_SUSPEND = 60
 AUTO_RESUME = TRUE
 MIN_CLUSTER_COUNT = 1
 MAX_CLUSTER_COUNT = 2
 SCALING_POLICY = 'ECONOMY'
 INITIALLY_SUSPENDED = TRUE;

-- Dropping DATA SHARE
USE ROLE ACCOUNTADMIN;
DROP SHARE IF EXISTS SFSENORTHAMERICA.EPLATA01.PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;
CREATE SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE COMMENT = 'PROVIDER_DB_SNOWFLAKE_SECURE_SHARE';
SHOW SHARES;

-- Creating a database
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE PROVIDER_DB COMMENT = 'Provider Database' DATA_RETENTION_TIME_IN_DAYS = 1;

-- Creating a Sales Table
CREATE OR REPLACE TABLE PROVIDER_DB.PUBLIC.SALES (
        id              number,
        country_id      varchar,
        sales_date      date,
        sales_amount    number
);

-- Adding some records to the table sales
INSERT INTO PROVIDER_DB.PUBLIC.SALES (id, country_id, sales_date, sales_amount) VALUES
 (1,'DE','2021-09-01',10901),
 (2,'DE','2021-10-01',11001),
 (3,'NL','2021-09-01',20901),
 (4,'NL','2021-10-01',21001),
 (5,'US','2021-09-01',30901),
 (6,'US','2021-10-01',31001);

-- Selecting off the new table sales
SELECT * FROM PROVIDER_DB.PUBLIC.SALES;

-- Add database to share
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE PROVIDER_DB TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;
GRANT USAGE ON SCHEMA PROVIDER_DB.PUBLIC TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;
GRANT SELECT ON TABLE PROVIDER_DB.PUBLIC.SALES TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;
ALTER SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE ADD ACCOUNTS = AEDQDYF.PZ90441;

SHOW GRANTS TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;

-- ********** ADD SHARE IN CONSUMER **********

-- Adding a new record
USE ROLE SYSADMIN;
INSERT INTO PROVIDER_DB.PUBLIC.SALES (id, country_id, sales_date, sales_amount) VALUES
 (20,'DE','2021-09-01',10901);

-- Advance: Creating a Policy mapping table
USE ROLE SYSADMIN;
CREATE OR REPLACE TABLE PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING (
    COUNTRY_ID      VARCHAR,
    ACCOUNT_NAME    VARCHAR
);

-- Inserting some records into the country_policy_mapping table
INSERT INTO PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING(COUNTRY_ID, ACCOUNT_NAME) VALUES
  ('DE','MJ38987'),
  ('NL','MJ38987'),
  ('US','MJ38987'),
  ('US','IG29426');

-- Selecting off the new table country_policy_mapping
SELECT * FROM PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING;

-- Creating a row access policy for the sales table
CREATE OR REPLACE ROW ACCESS POLICY PROVIDER_DB.PUBLIC.SIMPLE_POLICY AS (country_id VARCHAR) RETURNS BOOLEAN ->
  'MJ38987' = CURRENT_ACCOUNT()
      OR EXISTS (
            SELECT 1 FROM PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING mpt
            WHERE ACCOUNT_NAME = CURRENT_ACCOUNT()
             AND mpt.country_id = country_id
          )
;

-- Adding the row access policy to the sales table
ALTER TABLE PROVIDER_DB.PUBLIC.SALES
  ADD ROW ACCESS POLICY PROVIDER_DB.PUBLIC.SIMPLE_POLICY ON (COUNTRY_ID);

-- Selecting off-the-table sales (should return 6 records for the provider)
SELECT * FROM PROVIDER_DB.PUBLIC.SALES;

-- REVOKE ACCESS
USE ROLE ACCOUNTADMIN;
ALTER SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE REMOVE ACCOUNTS = AEDQDYF.PZ90441;