USE ROLE ACCOUNTADMIN;

-- Grant access to the S3 bucket to the SYSADMIN role
GRANT USAGE ON INTEGRATION S3_BUCKET_INTEGRATION TO ROLE SYSADMIN;

-- Create hackathon database
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE HACKATHON
 DATA_RETENTION_TIME_IN_DAYS = 2;

USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE HACKATHON_VW WITH
    WAREHOUSE_SIZE = 'X-SMALL' -- { XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE }
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = ECONOMY -- { STANDARD | ECONOMY }
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE -- { TRUE | FALSE };
    --MAX_CONCURRENCY_LEVEL = <num>
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0
    STATEMENT_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0
;
