USE ROLE SYSADMIN;
USE WAREHOUSE HACKATHON_VW;
USE DATABASE HACKATHON;
USE SCHEMA PUBLIC;

-- Create file format for json files
CREATE OR REPLACE FILE FORMAT HACKATHON.PUBLIC.FILE_FORMAT_JSON_GENERIC
 TYPE = 'JSON'
 ENABLE_OCTAL = FALSE
 ALLOW_DUPLICATE  = TRUE
 STRIP_OUTER_ARRAY = TRUE
 STRIP_NULL_VALUES = TRUE
 IGNORE_UTF8_ERRORS = FALSE;

-- Create stage for external files in S3
CREATE OR REPLACE STAGE S3_EXTERNAL_STAGE
  STORAGE_INTEGRATION = S3_BUCKET_INTEGRATION
  URL = 's3://snowflake-ep-hackathon/json/'
  FILE_FORMAT = HACKATHON.PUBLIC.FILE_FORMAT_JSON_GENERIC;

-- Listing files in stage
LIST @S3_EXTERNAL_STAGE;

-- Querying the files in stage
SELECT * FROM @HACKATHON.PUBLIC.S3_EXTERNAL_STAGE/SNOWBANK_PUBLIC_ACCOUNTS_1.json LIMIT 10;

SELECT $1:ACCESSIBLE_BALANCE::VARCHAR AS ACCESSIBLE_BALANCE,
       $1:ACCOUNT_BALANCE::VARCHAR AS ACCOUNT_BALANCE,
       $1:ACCOUNT_STATUS_CODE::VARCHAR AS ACCOUNT_STATUS_CODE,
       $1:ACCOUNT_UID::VARCHAR AS ACCOUNT_UID,
       $1:CDIC_HOLD_STATUS_CODE::VARCHAR AS CDIC_HOLD_STATUS_CODE,
       $1:CURRENCY_CODE::VARCHAR AS CURRENCY_CODE,
       $1:CURRENT_CDIC_HOLD_AMOUNT::VARCHAR AS CURRENT_CDIC_HOLD_AMOUNT,
       $1:DEPOSITOR_ID::VARCHAR AS DEPOSITOR_ID,
       $1:INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE::VARCHAR AS INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,
       $1:PRODUCT_CODE::VARCHAR AS PRODUCT_CODE,
       $1:REGISTERED_ACCOUNT_FLAG::VARCHAR AS REGISTERED_ACCOUNT_FLAG,
       $1:REGISTERED_PLAN_TYPE_CODE::VARCHAR AS REGISTERED_PLAN_TYPE_CODE,
       metadata$filename, metadata$file_row_number
FROM @HACKATHON.PUBLIC.S3_EXTERNAL_STAGE/SNOWBANK_PUBLIC_ACCOUNTS_1.json LIMIT 10;

-- Create table for external files in S3
CREATE OR REPLACE TABLE HACKATHON.PUBLIC.ACCOUNTS_RAW (
    ACCESSIBLE_BALANCE                         VARCHAR,
    ACCOUNT_BALANCE                            VARCHAR,
    ACCOUNT_STATUS_CODE                        VARCHAR,
    ACCOUNT_UID                                VARCHAR,
    CDIC_HOLD_STATUS_CODE                      VARCHAR,
    CURRENCY_CODE                              VARCHAR,
    CURRENT_CDIC_HOLD_AMOUNT                   VARCHAR,
    DEPOSITOR_ID                               VARCHAR,
    INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE VARCHAR,
    PRODUCT_CODE                               VARCHAR,
    REGISTERED_ACCOUNT_FLAG                    VARCHAR,
    REGISTERED_PLAN_TYPE_CODE                  VARCHAR,
    FILE_NAME                                  VARCHAR,
    FILE_ROW_NUMBER                            VARCHAR
);

-- Copy data from stage to table
COPY INTO HACKATHON.PUBLIC.ACCOUNTS_RAW (ACCESSIBLE_BALANCE,ACCOUNT_BALANCE,ACCOUNT_STATUS_CODE,
                        ACCOUNT_UID,CDIC_HOLD_STATUS_CODE,CURRENCY_CODE,
                        CURRENT_CDIC_HOLD_AMOUNT,DEPOSITOR_ID,
                        INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,PRODUCT_CODE,
                        REGISTERED_ACCOUNT_FLAG,REGISTERED_PLAN_TYPE_CODE,
                        FILE_NAME,FILE_ROW_NUMBER)
FROM (
    SELECT $1:ACCESSIBLE_BALANCE::VARCHAR AS ACCESSIBLE_BALANCE,
       $1:ACCOUNT_BALANCE::VARCHAR AS ACCOUNT_BALANCE,
       $1:ACCOUNT_STATUS_CODE::VARCHAR AS ACCOUNT_STATUS_CODE,
       $1:ACCOUNT_UID::VARCHAR AS ACCOUNT_UID,
       $1:CDIC_HOLD_STATUS_CODE::VARCHAR AS CDIC_HOLD_STATUS_CODE,
       $1:CURRENCY_CODE::VARCHAR AS CURRENCY_CODE,
       $1:CURRENT_CDIC_HOLD_AMOUNT::VARCHAR AS CURRENT_CDIC_HOLD_AMOUNT,
       $1:DEPOSITOR_ID::VARCHAR AS DEPOSITOR_ID,
       $1:INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE::VARCHAR AS INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,
       $1:PRODUCT_CODE::VARCHAR AS PRODUCT_CODE,
       $1:REGISTERED_ACCOUNT_FLAG::VARCHAR AS REGISTERED_ACCOUNT_FLAG,
       $1:REGISTERED_PLAN_TYPE_CODE::VARCHAR AS REGISTERED_PLAN_TYPE_CODE,
       metadata$filename::VARCHAR AS FILE_NAME,
       metadata$file_row_number::VARCHAR AS FILE_ROW_NUMBER
    FROM @HACKATHON.PUBLIC.S3_EXTERNAL_STAGE
)
FILE_FORMAT = HACKATHON.PUBLIC.FILE_FORMAT_JSON_GENERIC
PATTERN = '.*.json'
ON_ERROR = 'skip_file'
--PURGE = TRUE
;

-- Querying the table
SELECT * FROM HACKATHON.PUBLIC.ACCOUNTS_RAW LIMIT 10;
