USE ROLE SYSADMIN;

-- In Snowflake create a warehouse call notebooks
CREATE OR REPLACE WAREHOUSE NOTEBOOKS
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 1
  SCALING_POLICY = 'ECONOMY';

-- In Snowflake create a database call notebooks
CREATE OR REPLACE DATABASE NOTEBOOKS;

-- Create internally named stage
CREATE OR REPLACE STAGE NOTEBOOKS.PUBLIC.XLS_LAKE DIRECTORY = (ENABLE = TRUE);
